// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_Fawson.Models;

#nullable disable

namespace Mission06_Fawson.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Mission06_Fawson.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action/Sci-Fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "Mind-bending movie",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Comedy",
                            Director = "Wes Anderson",
                            Edited = false,
                            LentTo = "",
                            Notes = "My favorite",
                            Rating = "PG",
                            Title = "Fantastic Mr. Fox",
                            Year = 2009
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Comedy",
                            Director = "Ash Brannon",
                            Edited = false,
                            LentTo = "",
                            Notes = "Inspiring story",
                            Rating = "PG",
                            Title = "Surf's Up",
                            Year = 2007
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
